### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by sabrinaluo** [chemdemo/wechat-deleted-friends#1]
request https://web.wechat.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=ApH7-wunSwXAIFDLD3_1oawR@qrticket_0&uuid=YZNtn2D3_Q==&lang=zh_CN&scan=1452509138&fun=new error { [Error: socket hang up] code: 'ECONNRESET' }
Error: socket hang up

**Comment by chemdemo** [comment]
应该是之前的一个bug，现在fix了吧
