### ISSUE TITLE
建群失败：操作太频繁，请稍后再试。

### ISSUE THREAD

**Issue by wmfbravo** [chemdemo/wechat-deleted-friends#2]
正在查询删除你的好友...
建群失败：操作太频繁，请稍后再试。

**Comment by chemdemo** [comment]
洗洗睡吧 微信已经屏蔽接口了。。

**Comment by txdywy** [comment]
每次运行动态调整一下接口参数,比如每个group的人数就可以了.感觉是微信接口对完全参数相同的频繁请求做了限制.因为目前的逻辑每次将好友排序分组后结果是固定的.亲测一直频繁,将group member number改成10就可以跑了.不知将memberlist分组随机是不是能有一样的效果~

**Comment by chemdemo** [comment]
@txdywy 赞啊 我回头试试

**Comment by jtsky** [comment]
改了MAX_GROUP_NUM还是提示操作太频繁

**Comment by chemdemo** [comment]
@jtsky 改那个没用 微信是封接口 拉群不说话会被禁

**Comment by wmfbravo** [comment]
@chemdemo 3q.

**Comment by xxb** [comment]
所以结论是什么？没救了么？
