### ISSUE TITLE
TypeError: listener must be a function

### ISSUE THREAD

**Issue by jtsky** [chemdemo/wechat-deleted-friends#3]
运行的时候报TypeError: listener must be a function 错误

**Comment by chemdemo** [comment]
Node什么版本

**Comment by jtsky** [comment]
/_req.setTimeout(() => {
            reject(`request ${u} timeout`)
        }, 3000);_/ 
注释掉就可以了

**Comment by chemdemo** [comment]
谢谢提醒 是我改错了 已经fix
